### ISSUE TITLE
When mentioning "time" skarm responds with a very wrong time

### ISSUE THREAD

**Issue by Bardificer** [DragoniteSpam/SkarmBot#41]
![image](https://user-images.githubusercontent.com/39376345/164732820-1d40b5fa-9b94-4267-80d6-ce49927da297.png)

Mentioning "time" in a message that skarm can see will cause it to respond with a very wrong timestamp.
Using e!time and then e!utd does give the right, accurate, time.

**Comment by DragoniteSpam** [comment]
Currently the [e!time](https://github.com/DragoniteSpam/SkarmBot/blob/ef22830c6931848f2ad7611f3b297c097ebb3e55/javascript/commands.js#L551) command is (an admittedly not super) for showing the current unix timestamp integer, as promised, but the keyphrase ["what time"](https://github.com/DragoniteSpam/SkarmBot/blob/ef22830c6931848f2ad7611f3b297c097ebb3e55/javascript/keywords.js#L48) is one of the jokey responses that gives you a patently wrong answer. Do you reckon this is needlessly confusing and should be changed?

**Comment by ArgoTheNaut** [comment]
> Mentioning "time" in a message that skarm can see will cause it to respond with a very wrong timestamp. Using e!time and then e!utd does give the right, accurate, time.

yes
